[workspace]
authors = ["Kim Ng <kimleeng@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "uQCme"
platforms = ["osx-arm64"]
version = "0.2.0"

[tasks]
build = "rattler-build build --recipe recipe.yaml"
publish = "anaconda upload output/**/*.conda"
login = "anaconda login"

[dependencies]
rattler-build = ">=0.35.0"
anaconda-client = ">=1.12.0"
streamlit = ">=1.47.1,<2"
pandas = ">=2.3.1,<3"
plotly = ">=6.2.0,<7"
pyyaml = ">=6.0.2,<7"
openpyxl = ">=3.1.5,<4"
pytest = ">=9.0.1,<10"
python-build = ">=1.3.0,<2"
pydantic = ">=2.12.4,<3"
pandera = ">=0.26.1,<0.27"
pip = ">=24.0"
python = ">=3.12,<3.13"
setuptools = ">=69.0"
wheel = ">=0.42"
